### ISSUE TITLE
Certificate Generation

### ISSUE THREAD

**Issue by susantjasinski** [openbmc/phosphor-webui#60]

**Comment by gtmills** [comment]
@susantjasinski Can you add a description?

**Comment by jandraa** [comment]
In addition to the traditional 'certificate upload', users are able to obtain a certificate by generating one and soliciting a CSR (certificate signing request) via a signing authority. Users must provide certain info (ex. company name, country, city, email, etc.) and key info (ex. bit length), to generate a private key and a CSR. Once a certificate has been signed by an authority, this file needs to be placed on the BMC. (Currently discussing whether it needs to be downloaded and uploaded or if it can be automatically placed in the right location).

**Comment by jandraa** [comment]
**InVision prototype:** https://ibm.invisionapp.com/share/K8NYRVZVEC5#/319042048_1-_Generate_Certificates

Open questions: 
- [ ] How do users identify a certificate when there is more than one of a single type?
- [ ] How do users interact with the date? Why is knowing the exact valid from and valid until dates valuable vs the number of days until expiration? ('valid from - valid until' VS. 'X days left')
- [ ] What happens after a CSR has been generated? When and how is it accessed again and where should it live? 
- [ ] How / when is the private key uploaded to be part of the CSR? (if at all)
- [ ] Where are private keys stored? 
- [ ] Does each certificate have a different private key or do all of your certificates have the same private key because you are always you?
- [ ] How would it be beneficial to pre-populate CSR info for users? Could they pre-populate using the passphrase of a different certificate to copy the info?

**Comment by gtmills** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/22468

**Comment by derick-montague** [comment]
@gtmills - This is merged, should this story be closed?
